# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

stages:
  - test
  - run

before_script:
  - python --version  # For debugging
  
test:
  script:
    - python -m py_compile *.py

run:
  script:
    - python spotify-backup.py --format=json --dump=liked --token=$SPOTIFY_OAUTH_TOKEN output.json
  artifacts:
    paths:
      - output.json
  # trigger this job only "by-hand"
  when: manual

#pages:
#  script:
#    - mkdir public
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
