# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: $CI_REGISTRY/$CI_PROJECT_ROOT_NAMESPACE/$JSC_GRP_IMG_UBUNTU_24
variables:
  # https://docs.gitlab.com/ee/ci/pipelines/index.html#prefill-variables-in-manual-pipelines
  SPOTIFY_REDIRECT_URL:
    value: "http://127.0.0.1:43019/redirect#access_token=...."
    description: "redirect uri from login on https://accounts.spotify.com/authorize?response_type=token&client_id=5c098bcc800e45d49e476265bc9b6934&scope=playlist-read-private+playlist-read-collaborative+user-library-read&redirect_uri=http%3A%2F%2F127.0.0.1%3A43019%2Fredirect"

stages:
  - test
  - gather
  - deploy

before_script:
  - python --version  # For debugging
  - pip install markdown
  - pip install mkdocs mkdocs-material
  - mkdir -p public docs docs/artists docs/liked docs/playlists
  
test:
  script:
    - python -m py_compile *.py

get_data:
  stage: gather
  script:
    - python spotify-backup.py --format=json --dump=liked --redirect-url=$SPOTIFY_REDIRECT_URL liked.json
    - python spotify-backup.py --format=json --dump=playlists --redirect-url=$SPOTIFY_REDIRECT_URL playlists.json
    - python json2md.py  -i liked.json -o liked.md
    - python json2md.py  -i playlists.json -o playlists.md
    - python -m markdown liked.md -x extra -f liked.html
    - python -m markdown playlists.md -x extra -f playlists.html
  artifacts:
    expire_in: 1 day
    paths:
      - "*.md"
      - "*.json"
      - "*.html"
  # trigger this job only "by-hand"
  when: manual

pages:
  stage: deploy
  dependencies:
    - get_data
  script:
    - |
      # hide navigation at homepage
      cat <<EOF > docs/index.md
      ---
      hide:
        - toc
      ---
      EOF
    - cat liked.md >> docs/index.md
    - python parse-artists.py
    - mkdocs build --strict --no-directory-urls --site-dir ./public
  artifacts:
    expire_in: 1 day
    paths:
      - public/
  # trigger this job only "by-hand"
  when: manual
